# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Lei Chen
# Description of the Site
description: Make it work, make it right, make it fast.
# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: Learning, Creation, Happiness
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: /assets/images/title.jpg

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: mashirocl@gmail.com
facebook_username:
twitter_username: MashiroCl
instagram_username:
linkedin_username: lei-chen-a8a542227
github_username: MashiroCl
steam_username: 76561198336093131
youtube_channel_id:
reddit_username: 
behance_username:
dribbble_username: 
spotify_username:

# Google Analytics
google-analytics: /

# Disqus
disqus-shortname: /

# Name of the Author
author-name: Lei Chen
# URL for the Image of the Author
author-image: /assets/images/author.png
# 60 Words About the Author
author-about:
---
My name is Lei Chen, and I am a doctoral student at the Tokyo Institute of Technology, specializing in software engineering with a particular focus on software evolutions.
I received my B.S. degree in in Software Engineering from Dalian University of Technology (DUT) in Dalian, China, in 2020, and my M.S. degree in Computer Science from the Tokyo nstitute of Technology in Tokyo, Japan, in 2022.

Since 2022, I have been pursuing a Ph.D. at the Tokyo Institute of Technology under the supervision of Prof. Shinpei Hayashi. 
Additionally, I had the opportunity to serve as a collaborative researcher at the Università della Svizzera italiana (USI) in Switzerland from December 2023 to June 2024, under the guidance of Prof. Michele Lanza.

# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/MashiroCl

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
